filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: "PSR2"

    # Analyzes the size and structure of a PHP project.
    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - vendor
            - tests

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'

    php_loc:
        enabled: true
        excluded_dirs:
            - vendor
            - tests

    # Security Advisory Checker
    sensiolabs_security_checker: true

    # Code Coverage
    external_code_coverage: true